// Auto-generated by LibreLane
module dsm_and_freq_divider(
`ifdef USE_POWER_PINS
  inout VPWR,
  inout VGND,
`endif
  input freq_in,
  input rst,
  input sclk,
  input sdata,
  input en,
  output freq_out
);
endmodule
