/* Generated by Yosys 0.62 (git sha1 7326bb7d6641500ecb285c291a54a662cb1e76cf, clang++ 21.1.2 -fPIC -O3) */

module dsm_and_freq_divider(freq_in, rst, sclk, sdata, en, freq_out);
  input freq_in;
  wire freq_in;
  input rst;
  wire rst;
  input sclk;
  wire sclk;
  input sdata;
  wire sdata;
  input en;
  wire en;
  output freq_out;
  wire freq_out;
  wire _000_;
  wire _001_;
  wire _002_;
  wire _003_;
  wire _004_;
  wire _005_;
  wire _006_;
  wire _007_;
  wire _008_;
  wire _009_;
  wire _010_;
  wire _011_;
  wire _012_;
  wire _013_;
  wire _014_;
  wire _015_;
  wire _016_;
  wire _017_;
  wire _018_;
  wire _019_;
  wire _020_;
  wire _021_;
  wire _022_;
  wire _023_;
  wire _024_;
  wire _025_;
  wire _026_;
  wire _027_;
  wire _028_;
  wire _029_;
  wire _030_;
  wire _031_;
  wire _032_;
  wire _033_;
  wire _034_;
  wire _035_;
  wire _036_;
  wire _037_;
  wire _038_;
  wire _039_;
  wire _040_;
  wire _041_;
  wire _042_;
  wire _043_;
  wire _044_;
  wire _045_;
  wire _046_;
  wire _047_;
  wire _048_;
  wire _049_;
  wire _050_;
  wire _051_;
  wire _052_;
  wire _053_;
  wire _054_;
  wire _055_;
  wire _056_;
  wire _057_;
  wire _058_;
  wire _059_;
  wire _060_;
  wire _061_;
  wire _062_;
  wire _063_;
  wire _064_;
  wire _065_;
  wire _066_;
  wire _067_;
  wire _068_;
  wire _069_;
  wire _070_;
  wire _071_;
  wire _072_;
  wire _073_;
  wire _074_;
  wire _075_;
  wire _076_;
  wire _077_;
  wire _078_;
  wire _079_;
  wire _080_;
  wire _081_;
  wire _082_;
  wire _083_;
  wire _084_;
  wire _085_;
  wire _086_;
  wire _087_;
  wire _088_;
  wire _089_;
  wire _090_;
  wire _091_;
  wire _092_;
  wire _093_;
  wire _094_;
  wire _095_;
  wire _096_;
  wire _097_;
  wire _098_;
  wire _099_;
  wire _100_;
  wire _101_;
  wire _102_;
  wire _103_;
  wire _104_;
  wire _105_;
  wire _106_;
  wire _107_;
  wire _108_;
  wire _109_;
  wire _110_;
  wire _111_;
  wire _112_;
  wire _113_;
  wire _114_;
  wire _115_;
  wire _116_;
  wire \data_word[0] ;
  wire \data_word[1] ;
  wire \data_word[2] ;
  wire \data_word[3] ;
  wire \data_word[4] ;
  wire \data_word[5] ;
  wire \data_word[6] ;
  wire \data_word[7] ;
  wire \data_word[8] ;
  wire \u_dsm.integrator[0] ;
  wire \u_dsm.integrator[1] ;
  wire \u_dsm.integrator[2] ;
  wire \u_dsm.integrator[3] ;
  wire \u_dsm.integrator[4] ;
  wire \u_dsm.integrator[5] ;
  wire \u_dsm.integrator[6] ;
  wire \u_dsm.integrator[7] ;
  wire \u_dsm.integrator[8] ;
  wire \uut.b ;
  wire \uut.c ;
  wire \uut.clk_jk ;
  wire \uut.d ;
  wire \uut.div4.dff1.d ;
  wire \uut.div4.dff1.q ;
  wire \uut.div4.dff2.d ;
  wire \uut.div4.dff2.q ;
  wire \uut.mod7.jk1.d_in ;
  wire \uut.mod7.jk2.d_in ;
  wire \uut.mod7.jk3.d_in ;
  wire \uut.out_stg.dff_out.d ;
  wire \uut.pre45.d1 ;
  wire \uut.pre45.d2 ;
  wire \uut.pre45.d3 ;
  wire \uut.pre45.ff1.q ;
  sg13g2_mux2_1 _117_ (
    .A0(\data_word[8] ),
    .A1(\data_word[7] ),
    .S(en),
    .X(_044_)
  );
  sg13g2_mux2_1 _118_ (
    .A0(\data_word[7] ),
    .A1(\data_word[6] ),
    .S(en),
    .X(_043_)
  );
  sg13g2_mux2_1 _119_ (
    .A0(\data_word[6] ),
    .A1(\data_word[5] ),
    .S(en),
    .X(_042_)
  );
  sg13g2_mux2_1 _120_ (
    .A0(\data_word[5] ),
    .A1(\data_word[4] ),
    .S(en),
    .X(_041_)
  );
  sg13g2_mux2_1 _121_ (
    .A0(\data_word[4] ),
    .A1(\data_word[3] ),
    .S(en),
    .X(_040_)
  );
  sg13g2_mux2_1 _122_ (
    .A0(\data_word[3] ),
    .A1(\data_word[2] ),
    .S(en),
    .X(_039_)
  );
  sg13g2_mux2_1 _123_ (
    .A0(\data_word[2] ),
    .A1(\data_word[1] ),
    .S(en),
    .X(_038_)
  );
  sg13g2_mux2_1 _124_ (
    .A0(\data_word[1] ),
    .A1(\data_word[0] ),
    .S(en),
    .X(_037_)
  );
  sg13g2_mux2_1 _125_ (
    .A0(\data_word[0] ),
    .A1(sdata),
    .S(en),
    .X(_036_)
  );
  sg13g2_a21oi_1 _126_ (
    .A1(\uut.d ),
    .A2(\uut.c ),
    .B1(\uut.b ),
    .Y(\uut.mod7.jk1.d_in )
  );
  sg13g2_nand2_1 _127_ (
    .A(\uut.d ),
    .B(\uut.c ),
    .Y(_113_)
  );
  sg13g2_o21ai_1 _128_ (
    .A1(\uut.c ),
    .A2(\uut.b ),
    .B1(_113_),
    .Y(_114_)
  );
  sg13g2_a21oi_1 _129_ (
    .A1(\uut.c ),
    .A2(\uut.b ),
    .B1(_114_),
    .Y(\uut.mod7.jk2.d_in )
  );
  sg13g2_a21oi_1 _130_ (
    .A1(\uut.c ),
    .A2(\uut.b ),
    .B1(\uut.d ),
    .Y(_115_)
  );
  sg13g2_a21oi_1 _131_ (
    .A1(\uut.d ),
    .A2(\uut.c ),
    .B1(_115_),
    .Y(\uut.mod7.jk3.d_in )
  );
  sg13g2_nor2_1 _132_ (
    .A(\uut.d ),
    .B(\uut.c ),
    .Y(_116_)
  );
  sg13g2_nor3_1 _133_ (
    .A(\uut.b ),
    .B(\uut.clk_jk ),
    .C(_116_),
    .Y(_045_)
  );
  sg13g2_o21ai_1 _134_ (
    .A1(\u_dsm.integrator[8] ),
    .A2(_113_),
    .B1(_045_),
    .Y(_046_)
  );
  sg13g2_and2_1 _135_ (
    .A(\uut.pre45.d3 ),
    .B(_046_),
    .X(\uut.pre45.d1 )
  );
  sg13g2_xor2_1 _136_ (
    .A(\u_dsm.integrator[8] ),
    .B(\u_dsm.integrator[0] ),
    .X(_047_)
  );
  sg13g2_nand2b_1 _137_ (
    .A_N(_047_),
    .B(\data_word[0] ),
    .Y(_048_)
  );
  sg13g2_nor2_1 _138_ (
    .A(\u_dsm.integrator[8] ),
    .B(\u_dsm.integrator[0] ),
    .Y(_049_)
  );
  sg13g2_xor2_1 _139_ (
    .A(\data_word[1] ),
    .B(\u_dsm.integrator[8] ),
    .X(_050_)
  );
  sg13g2_xnor2_1 _140_ (
    .A(\u_dsm.integrator[1] ),
    .B(_050_),
    .Y(_051_)
  );
  sg13g2_xor2_1 _141_ (
    .A(_049_),
    .B(_051_),
    .X(_052_)
  );
  sg13g2_xnor2_1 _142_ (
    .A(_048_),
    .B(_052_),
    .Y(_001_)
  );
  sg13g2_inv_1 _143_ (
    .A(_048_),
    .Y(_053_)
  );
  sg13g2_nor2_1 _144_ (
    .A(_049_),
    .B(_051_),
    .Y(_054_)
  );
  sg13g2_a21o_2 _145_ (
    .A1(_053_),
    .A2(_052_),
    .B1(_054_),
    .X(_055_)
  );
  sg13g2_and2_1 _146_ (
    .A(\data_word[1] ),
    .B(\u_dsm.integrator[8] ),
    .X(_056_)
  );
  sg13g2_a21oi_1 _147_ (
    .A1(\u_dsm.integrator[1] ),
    .A2(_050_),
    .B1(_056_),
    .Y(_057_)
  );
  sg13g2_xor2_1 _148_ (
    .A(\data_word[2] ),
    .B(\u_dsm.integrator[8] ),
    .X(_058_)
  );
  sg13g2_xnor2_1 _149_ (
    .A(\u_dsm.integrator[2] ),
    .B(_058_),
    .Y(_059_)
  );
  sg13g2_xor2_1 _150_ (
    .A(_057_),
    .B(_059_),
    .X(_060_)
  );
  sg13g2_xor2_1 _151_ (
    .A(_055_),
    .B(_060_),
    .X(_002_)
  );
  sg13g2_and2_1 _152_ (
    .A(\data_word[2] ),
    .B(\u_dsm.integrator[8] ),
    .X(_061_)
  );
  sg13g2_a21oi_1 _153_ (
    .A1(\u_dsm.integrator[2] ),
    .A2(_058_),
    .B1(_061_),
    .Y(_062_)
  );
  sg13g2_xor2_1 _154_ (
    .A(\data_word[3] ),
    .B(\u_dsm.integrator[8] ),
    .X(_063_)
  );
  sg13g2_xnor2_1 _155_ (
    .A(\u_dsm.integrator[3] ),
    .B(_063_),
    .Y(_064_)
  );
  sg13g2_xor2_1 _156_ (
    .A(_062_),
    .B(_064_),
    .X(_065_)
  );
  sg13g2_nor2_1 _157_ (
    .A(_057_),
    .B(_059_),
    .Y(_066_)
  );
  sg13g2_a21oi_1 _158_ (
    .A1(_055_),
    .A2(_060_),
    .B1(_066_),
    .Y(_067_)
  );
  sg13g2_xnor2_1 _159_ (
    .A(_065_),
    .B(_067_),
    .Y(_003_)
  );
  sg13g2_and2_1 _160_ (
    .A(_060_),
    .B(_065_),
    .X(_068_)
  );
  sg13g2_nand2_1 _161_ (
    .A(_062_),
    .B(_064_),
    .Y(_069_)
  );
  sg13g2_nor2_1 _162_ (
    .A(_062_),
    .B(_064_),
    .Y(_070_)
  );
  sg13g2_a21o_2 _163_ (
    .A1(_066_),
    .A2(_069_),
    .B1(_070_),
    .X(_071_)
  );
  sg13g2_a21oi_2 _164_ (
    .A1(_055_),
    .A2(_068_),
    .B1(_071_),
    .Y(_072_)
  );
  sg13g2_nand2_1 _165_ (
    .A(\data_word[3] ),
    .B(\u_dsm.integrator[8] ),
    .Y(_073_)
  );
  sg13g2_nand2_1 _166_ (
    .A(\u_dsm.integrator[3] ),
    .B(_063_),
    .Y(_074_)
  );
  sg13g2_xor2_1 _167_ (
    .A(\data_word[4] ),
    .B(\u_dsm.integrator[8] ),
    .X(_075_)
  );
  sg13g2_xnor2_1 _168_ (
    .A(\u_dsm.integrator[4] ),
    .B(_075_),
    .Y(_076_)
  );
  sg13g2_a21oi_1 _169_ (
    .A1(_073_),
    .A2(_074_),
    .B1(_076_),
    .Y(_077_)
  );
  sg13g2_nand3_1 _170_ (
    .A(_073_),
    .B(_074_),
    .C(_076_),
    .Y(_078_)
  );
  sg13g2_nor2b_1 _171_ (
    .A(_077_),
    .B_N(_078_),
    .Y(_079_)
  );
  sg13g2_xnor2_1 _172_ (
    .A(_072_),
    .B(_079_),
    .Y(_004_)
  );
  sg13g2_nand2_1 _173_ (
    .A(\data_word[4] ),
    .B(\u_dsm.integrator[8] ),
    .Y(_080_)
  );
  sg13g2_nand2_1 _174_ (
    .A(\u_dsm.integrator[4] ),
    .B(_075_),
    .Y(_081_)
  );
  sg13g2_xor2_1 _175_ (
    .A(\data_word[5] ),
    .B(\u_dsm.integrator[8] ),
    .X(_082_)
  );
  sg13g2_xnor2_1 _176_ (
    .A(\u_dsm.integrator[5] ),
    .B(_082_),
    .Y(_083_)
  );
  sg13g2_and3_1 _177_ (
    .A(_080_),
    .B(_081_),
    .C(_083_),
    .X(_084_)
  );
  sg13g2_a21oi_1 _178_ (
    .A1(_080_),
    .A2(_081_),
    .B1(_083_),
    .Y(_085_)
  );
  sg13g2_nor2_1 _179_ (
    .A(_084_),
    .B(_085_),
    .Y(_086_)
  );
  sg13g2_a21o_1 _180_ (
    .A1(_055_),
    .A2(_068_),
    .B1(_071_),
    .X(_087_)
  );
  sg13g2_a21oi_1 _181_ (
    .A1(_087_),
    .A2(_079_),
    .B1(_077_),
    .Y(_088_)
  );
  sg13g2_xnor2_1 _182_ (
    .A(_086_),
    .B(_088_),
    .Y(_005_)
  );
  sg13g2_nand2_1 _183_ (
    .A(_079_),
    .B(_086_),
    .Y(_089_)
  );
  sg13g2_nand3_1 _184_ (
    .A(_080_),
    .B(_081_),
    .C(_083_),
    .Y(_090_)
  );
  sg13g2_a21oi_1 _185_ (
    .A1(_077_),
    .A2(_090_),
    .B1(_085_),
    .Y(_091_)
  );
  sg13g2_o21ai_1 _186_ (
    .A1(_072_),
    .A2(_089_),
    .B1(_091_),
    .Y(_092_)
  );
  sg13g2_nand2_1 _187_ (
    .A(\data_word[5] ),
    .B(\u_dsm.integrator[8] ),
    .Y(_093_)
  );
  sg13g2_nand2_1 _188_ (
    .A(\u_dsm.integrator[5] ),
    .B(_082_),
    .Y(_094_)
  );
  sg13g2_xor2_1 _189_ (
    .A(\data_word[6] ),
    .B(\u_dsm.integrator[8] ),
    .X(_095_)
  );
  sg13g2_xnor2_1 _190_ (
    .A(\u_dsm.integrator[6] ),
    .B(_095_),
    .Y(_096_)
  );
  sg13g2_a21oi_1 _191_ (
    .A1(_093_),
    .A2(_094_),
    .B1(_096_),
    .Y(_097_)
  );
  sg13g2_nand3_1 _192_ (
    .A(_093_),
    .B(_094_),
    .C(_096_),
    .Y(_098_)
  );
  sg13g2_nor2b_1 _193_ (
    .A(_097_),
    .B_N(_098_),
    .Y(_099_)
  );
  sg13g2_xor2_1 _194_ (
    .A(_092_),
    .B(_099_),
    .X(_006_)
  );
  sg13g2_nand2_1 _195_ (
    .A(\data_word[6] ),
    .B(\u_dsm.integrator[8] ),
    .Y(_100_)
  );
  sg13g2_nand2_1 _196_ (
    .A(\u_dsm.integrator[6] ),
    .B(_095_),
    .Y(_101_)
  );
  sg13g2_xnor2_1 _197_ (
    .A(\data_word[7] ),
    .B(\u_dsm.integrator[8] ),
    .Y(_102_)
  );
  sg13g2_xnor2_1 _198_ (
    .A(\u_dsm.integrator[7] ),
    .B(_102_),
    .Y(_103_)
  );
  sg13g2_a21oi_1 _199_ (
    .A1(_100_),
    .A2(_101_),
    .B1(_103_),
    .Y(_104_)
  );
  sg13g2_nand3_1 _200_ (
    .A(_100_),
    .B(_101_),
    .C(_103_),
    .Y(_105_)
  );
  sg13g2_nor2b_1 _201_ (
    .A(_104_),
    .B_N(_105_),
    .Y(_106_)
  );
  sg13g2_a21oi_1 _202_ (
    .A1(_092_),
    .A2(_099_),
    .B1(_097_),
    .Y(_107_)
  );
  sg13g2_xnor2_1 _203_ (
    .A(_106_),
    .B(_107_),
    .Y(_007_)
  );
  sg13g2_and2_1 _204_ (
    .A(_099_),
    .B(_106_),
    .X(_108_)
  );
  sg13g2_a221oi_1 _205_ (
    .A1(_097_),
    .A2(_105_),
    .B1(_108_),
    .B2(_092_),
    .C1(_104_),
    .Y(_109_)
  );
  sg13g2_nor2b_1 _206_ (
    .A(\u_dsm.integrator[8] ),
    .B_N(\data_word[7] ),
    .Y(_110_)
  );
  sg13g2_a21oi_1 _207_ (
    .A1(\u_dsm.integrator[7] ),
    .A2(_102_),
    .B1(_110_),
    .Y(_111_)
  );
  sg13g2_xor2_1 _208_ (
    .A(\data_word[8] ),
    .B(_111_),
    .X(_112_)
  );
  sg13g2_xnor2_1 _209_ (
    .A(_109_),
    .B(_112_),
    .Y(_008_)
  );
  sg13g2_xnor2_1 _210_ (
    .A(\data_word[0] ),
    .B(_047_),
    .Y(_000_)
  );
  sg13g2_inv_1 _211_ (
    .A(\uut.pre45.ff1.q ),
    .Y(\uut.pre45.d2 )
  );
  sg13g2_inv_1 _212_ (
    .A(\uut.div4.dff2.q ),
    .Y(\uut.div4.dff2.d )
  );
  sg13g2_inv_1 _213_ (
    .A(freq_out),
    .Y(\uut.out_stg.dff_out.d )
  );
  sg13g2_inv_1 _214_ (
    .A(\uut.div4.dff1.q ),
    .Y(\uut.div4.dff1.d )
  );
  sg13g2_inv_1 _215_ (
    .A(rst),
    .Y(_009_)
  );
  sg13g2_inv_1 _216_ (
    .A(rst),
    .Y(_010_)
  );
  sg13g2_inv_1 _217_ (
    .A(rst),
    .Y(_011_)
  );
  sg13g2_inv_1 _218_ (
    .A(rst),
    .Y(_012_)
  );
  sg13g2_inv_1 _219_ (
    .A(rst),
    .Y(_013_)
  );
  sg13g2_inv_1 _220_ (
    .A(rst),
    .Y(_014_)
  );
  sg13g2_inv_1 _221_ (
    .A(rst),
    .Y(_015_)
  );
  sg13g2_inv_1 _222_ (
    .A(rst),
    .Y(_016_)
  );
  sg13g2_inv_1 _223_ (
    .A(rst),
    .Y(_017_)
  );
  sg13g2_inv_1 _224_ (
    .A(rst),
    .Y(_018_)
  );
  sg13g2_inv_1 _225_ (
    .A(rst),
    .Y(_019_)
  );
  sg13g2_inv_1 _226_ (
    .A(rst),
    .Y(_020_)
  );
  sg13g2_inv_1 _227_ (
    .A(rst),
    .Y(_021_)
  );
  sg13g2_inv_1 _228_ (
    .A(rst),
    .Y(_022_)
  );
  sg13g2_inv_1 _229_ (
    .A(rst),
    .Y(_023_)
  );
  sg13g2_inv_1 _230_ (
    .A(rst),
    .Y(_024_)
  );
  sg13g2_inv_1 _231_ (
    .A(rst),
    .Y(_025_)
  );
  sg13g2_inv_1 _232_ (
    .A(rst),
    .Y(_026_)
  );
  sg13g2_inv_1 _233_ (
    .A(rst),
    .Y(_027_)
  );
  sg13g2_inv_1 _234_ (
    .A(rst),
    .Y(_028_)
  );
  sg13g2_inv_1 _235_ (
    .A(rst),
    .Y(_029_)
  );
  sg13g2_inv_1 _236_ (
    .A(rst),
    .Y(_030_)
  );
  sg13g2_inv_1 _237_ (
    .A(rst),
    .Y(_031_)
  );
  sg13g2_inv_1 _238_ (
    .A(rst),
    .Y(_032_)
  );
  sg13g2_inv_1 _239_ (
    .A(rst),
    .Y(_033_)
  );
  sg13g2_inv_1 _240_ (
    .A(rst),
    .Y(_034_)
  );
  sg13g2_inv_1 _241_ (
    .A(rst),
    .Y(_035_)
  );
  sg13g2_dfrbpq_1 _242_ (
    .CLK(sclk),
    .D(_036_),
    .Q(\data_word[0] ),
    .RESET_B(_009_)
  );
  sg13g2_dfrbpq_1 _243_ (
    .CLK(sclk),
    .D(_037_),
    .Q(\data_word[1] ),
    .RESET_B(_010_)
  );
  sg13g2_dfrbpq_1 _244_ (
    .CLK(sclk),
    .D(_038_),
    .Q(\data_word[2] ),
    .RESET_B(_011_)
  );
  sg13g2_dfrbpq_1 _245_ (
    .CLK(sclk),
    .D(_039_),
    .Q(\data_word[3] ),
    .RESET_B(_012_)
  );
  sg13g2_dfrbpq_1 _246_ (
    .CLK(sclk),
    .D(_040_),
    .Q(\data_word[4] ),
    .RESET_B(_013_)
  );
  sg13g2_dfrbpq_1 _247_ (
    .CLK(sclk),
    .D(_041_),
    .Q(\data_word[5] ),
    .RESET_B(_014_)
  );
  sg13g2_dfrbpq_1 _248_ (
    .CLK(sclk),
    .D(_042_),
    .Q(\data_word[6] ),
    .RESET_B(_015_)
  );
  sg13g2_dfrbpq_1 _249_ (
    .CLK(sclk),
    .D(_043_),
    .Q(\data_word[7] ),
    .RESET_B(_016_)
  );
  sg13g2_dfrbpq_1 _250_ (
    .CLK(sclk),
    .D(_044_),
    .Q(\data_word[8] ),
    .RESET_B(_017_)
  );
  sg13g2_dfrbpq_1 _251_ (
    .CLK(freq_out),
    .D(_000_),
    .Q(\u_dsm.integrator[0] ),
    .RESET_B(_018_)
  );
  sg13g2_dfrbpq_1 _252_ (
    .CLK(freq_out),
    .D(_001_),
    .Q(\u_dsm.integrator[1] ),
    .RESET_B(_019_)
  );
  sg13g2_dfrbpq_1 _253_ (
    .CLK(freq_out),
    .D(_002_),
    .Q(\u_dsm.integrator[2] ),
    .RESET_B(_020_)
  );
  sg13g2_dfrbpq_1 _254_ (
    .CLK(freq_out),
    .D(_003_),
    .Q(\u_dsm.integrator[3] ),
    .RESET_B(_021_)
  );
  sg13g2_dfrbpq_1 _255_ (
    .CLK(freq_out),
    .D(_004_),
    .Q(\u_dsm.integrator[4] ),
    .RESET_B(_022_)
  );
  sg13g2_dfrbpq_1 _256_ (
    .CLK(freq_out),
    .D(_005_),
    .Q(\u_dsm.integrator[5] ),
    .RESET_B(_023_)
  );
  sg13g2_dfrbpq_1 _257_ (
    .CLK(freq_out),
    .D(_006_),
    .Q(\u_dsm.integrator[6] ),
    .RESET_B(_024_)
  );
  sg13g2_dfrbpq_1 _258_ (
    .CLK(freq_out),
    .D(_007_),
    .Q(\u_dsm.integrator[7] ),
    .RESET_B(_025_)
  );
  sg13g2_dfrbpq_1 _259_ (
    .CLK(freq_out),
    .D(_008_),
    .Q(\u_dsm.integrator[8] ),
    .RESET_B(_026_)
  );
  sg13g2_dfrbpq_1 _260_ (
    .CLK(\uut.d ),
    .D(\uut.out_stg.dff_out.d ),
    .Q(freq_out),
    .RESET_B(_027_)
  );
  sg13g2_dfrbpq_1 _261_ (
    .CLK(\uut.clk_jk ),
    .D(\uut.mod7.jk1.d_in ),
    .Q(\uut.b ),
    .RESET_B(_028_)
  );
  sg13g2_dfrbpq_1 _262_ (
    .CLK(\uut.clk_jk ),
    .D(\uut.mod7.jk2.d_in ),
    .Q(\uut.c ),
    .RESET_B(_029_)
  );
  sg13g2_dfrbpq_1 _263_ (
    .CLK(\uut.clk_jk ),
    .D(\uut.mod7.jk3.d_in ),
    .Q(\uut.d ),
    .RESET_B(_030_)
  );
  sg13g2_dfrbpq_1 _264_ (
    .CLK(\uut.div4.dff2.q ),
    .D(\uut.pre45.d1 ),
    .Q(\uut.pre45.ff1.q ),
    .RESET_B(_031_)
  );
  sg13g2_dfrbpq_1 _265_ (
    .CLK(\uut.div4.dff2.q ),
    .D(\uut.pre45.d2 ),
    .Q(\uut.pre45.d3 ),
    .RESET_B(_032_)
  );
  sg13g2_dfrbpq_1 _266_ (
    .CLK(\uut.div4.dff2.q ),
    .D(\uut.pre45.d3 ),
    .Q(\uut.clk_jk ),
    .RESET_B(_033_)
  );
  sg13g2_dfrbpq_1 _267_ (
    .CLK(freq_in),
    .D(\uut.div4.dff1.d ),
    .Q(\uut.div4.dff1.q ),
    .RESET_B(_034_)
  );
  sg13g2_dfrbpq_1 _268_ (
    .CLK(\uut.div4.dff1.q ),
    .D(\uut.div4.dff2.d ),
    .Q(\uut.div4.dff2.q ),
    .RESET_B(_035_)
  );
endmodule
